image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - apt-get update && apt-get install -y chromium
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

build:
  stage: build
  script:
    - npm run build -- --configuration production
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - main