image: node:latest

stages:
  - prepare
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_dependencies:
  stage: prepare
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y wget gnupg
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
    - apt-get update
    - apt-get install -y google-chrome-stable
  script:
    - CHROME_BIN=/usr/bin/google-chrome npm run test:ci

build:
  stage: build
  script:
    - npm run build -- --configuration production --base-href="https://<digibee_developer>.gitlab.io/<diamond_erp>/"
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r dist/<diamond_erp>/* public/
  artifacts:
    paths:
      - public
  only:
    - main

# image: node:latest

# stages:
#   - prepare
#   - test
#   - build
#   - deploy

# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - node_modules/

# install_dependencies:
#   stage: prepare
#   script:
#     - npm ci
#   artifacts:
#     paths:
#       - node_modules/

# test:
#   stage: test
#   before_script:
#     - apt-get update
#     - apt-get install -y wget gnupg
#     - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#     - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
#     - apt-get update
#     - apt-get install -y google-chrome-stable
#   script:
#     - CHROME_BIN=/usr/bin/google-chrome npm run test:ci

# build:
#   stage: build
#   script:
#     - npm run build -- --configuration production
#   artifacts:
#     paths:
#       - dist/

# deploy:
#   stage: deploy
#   script:
#     - npm install -g firebase-tools
#     - firebase deploy --token $FIREBASE_TOKEN
#   only:
#     - main