// constants.ts
export const CONSTANT = { 
    passwordPattern: /^[[a-zA-Z0-9]+[0-9]{3,}$/,
    API_BASE_URL: 'http://localhost:5000/api/login',
    DASHBOARD_ROUTE: '/dashboard',
    TOKEN_KEY: 'token',
    LOGIN_SUCCESSFUL: 'Login Successful',
    FAILURE_WHILE_LOGIN: 'Failure while login',
    LOGIN_ERROR: 'An error occurred during login',
    SUPER_ADMIN_LOGGED_IN: 'SuperAdmin logged in:',
    COMPANY_LOGGED_IN: 'Company logged in:',
    LOGGED_IN_COMPANY_ID: 'loggedInCompanyId',
    OPERATOR_LOGGED_IN: 'Operator logged in:',
    ERROR_LOGIN: 'Login error:',
    SUPERADMIN: 'superadmin',
    COMPANY: 'company',
    OPERATOR: 'operator',
    ROLES: ['Role 1', 'Role 2', 'Role 3'],
    ROLE_KEYS: ['role1', 'role2', 'role3'],
    OPERATORS_DATA_KEY: 'operatorsData',
    OPERATOR_NAME_KEY: 'operatorName',
    OPERATOR_ROLE_KEY: 'operatorRole',
    PHONE_KEY: 'phone',
    ROLES_KEY: 'roles',
    ERROR_FETCHING_OPERATORS: 'Error fetching operator data:',
    ERROR_ADDING_OPERATOR: 'Error adding new operator:',
    ERROR_DELETING_OPERATOR: 'Error deleting operator:',
    ERROR_UPDATING_OPERATOR: 'Error updating operator:',
    CREDENTIALS_KEY: 'credentials',
    API_OPERATOR_URL: 'http://localhost:5000/api/operators',
    API_OPERATOR_ADD_URL: 'http://localhost:5000/api/operator',
    ITEMS_PER_PAGE: 5,
    ROLE_1: 'role1',
    ROLE_2: 'role2',
    ROLE_3: 'role3',
    ROLE1: 'Role 1',
    ROLE2: 'Role 2',
    ROLE3: 'Role 3',
    RETRIEVED_OPERATOR_ROLE: 'Retrieved operatorRole',
    RETRIEVED_OPERATOR_NAME: 'Retrieved operatorName',
    INWARDS_PATH: '/inwards',
    COMPARE_PATH: '/compare',
    OUTWARDS_PATH: '/outwards'
 }