// constants.ts
export const CONSTANT = { 
    passwordPattern: /^[[a-zA-Z0-9]+[0-9]{3,}$/,
    API_BASE_URL: 'http://localhost:5000/api/login',
    DASHBOARD_ROUTE: '/dashboard',
    TOKEN_KEY: 'token',
    LOGIN_SUCCESSFUL: 'Login Successful',
    FAILURE_WHILE_LOGIN: 'Failure while login',
    LOGIN_ERROR: 'An error occurred during login',
    SUPER_ADMIN_LOGGED_IN: 'SuperAdmin logged in:',
    COMPANY_LOGGED_IN: 'Company logged in:',
    OPERATOR_LOGGED_IN: 'Operator logged in:',
    ERROR_LOGIN: 'Login error:',
    SUPERADMIN: 'superadmin',
    COMPANY: 'company',
    OPERATOR: 'operator',
    ROLES: ['Role 1', 'Role 2', 'Role 3'],
    ROLE_KEYS: ['role1', 'role2', 'role3'],
    OPERATORS_DATA_KEY: 'operatorsData',
    OPERATOR_NAME_KEY: 'operatorName',
    PHONE_KEY: 'phone',
    ROLES_KEY: 'roles',
    ERROR_FETCHING_OPERATORS: 'Error fetching operator data:',
    CREDENTIALS_KEY: 'credentials',
    API_OPERATOR_URL: 'http://localhost:5000/api/operators',
 }