name: CI/CD for Angular Project

on:
  push:
    branches: [ template_ui ]
  pull_request:
    branches: [ template_ui ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: template_ui

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test -- --configuration=ci

    - name: Build
      run: npm run build -- --prod

    - name: Prepare for deployment
      run: |
        mkdir public
        cp -R dist/coreui-free-angular-admin-template/* public/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./public