name: CI/CD for Angular Project

on:
  push:
    branches: [ template_ui ]
  pull_request:
    branches: [ template_ui ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: template_ui

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Check Node.js version
      run: node --version
    - name: Check npm version
      run: npm --version

    - name: Install dependencies
      run: npm ci

    - name: List installed packages
      run: npm list --depth=0

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Show Angular version
      run: ng version

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless --no-progress
    - name: Build
      run: npm run build -- --configuration production

    - name: Update base href
      run: sed -i 's/<base href="\/">/<base href="\/diamond123\/">/g' dist/coreui-free-angular-admin-template/index.html

    - name: Prepare for deployment
      run: |
        mkdir public
        cp -R dist/coreui-free-angular-admin-template/* public/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages 